name: Build and Test Cookbiik

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Display softuni username
      run: echo "velinilev"
    - name: Checkout the reposotory
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependecies
      run: npm install
    - name: Start
        run: npm run start &
    - name: Run Unit tests
      run: npm run test:unit
